### PR TITLE
Feature/88 vda name registry multi sign on mumbai

### LINKED ISSUE #88: [vda-name-registry] Upgrade to use multi-sign on Mumbai
We need to ensure the smart contract is compatible with [OpenZeppelin Defender](https://docs.openzeppelin.com/defender/guide-upgrades).

## Outcome:

1. [ ] Ryan and Chris can setup a multi-sig Gnosis Safe
2. [ ] The smart contract `owner` can be switched to the multi-sig Gnosis Safe
3. [ ] Gnosis Safe can call smart contract methods as `owner`
4. [ ] Gnosis Safe can upgrade the smart contract with a new version

## Key steps:

1. [x] @ITStar10 verify the smart contract is compatible with [OpenZeppelin Defender](https://docs.openzeppelin.com/defender/guide-upgrades)
2. [x] @ITStar10 create a Gnosis safe and test the multi-sig Gnosis Safe
3. [ ] @tahpot and @ryank000 setup multi-sig Gnosis Safe (Verida Mumbai Safe)
4. [ ] @ITStar10 change contract owner to `Verida Mumbai Safe`
5. [ ] @tahpot and @ryank000 test calling `owner` method
6. [ ] @tahpot and @ryank000 test deploying a contract upgrade

### PR DESCRIPTION
**Pull request by ITStar10**

### CODE REVIEW

**Comment by tahpot** [comment]
I can't test this due to this error:

```
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: polygonmainnet - Expected string, received undefined
  * Invalid account: #0 for network: polygontestnet - Expected string, received undefined
```

Please update this PR description with the issue it close, more information about the change and how to test.

**Comment by tahpot** [comment]
> I can't test this due to this error:
> 
> ```
> Error HH8: There's one or more errors in your config file:
> 
>   * Invalid account: #0 for network: polygonmainnet - Expected string, received undefined
>   * Invalid account: #0 for network: polygontestnet - Expected string, received undefined
> ```
> 
> Please update this PR description with the issue it close, more information about the change and how to test.

This is now working with a `.env` file.

@ITStar10 will add information in the README.md on how to configure the `.env` with a sample `.env` file.

**Comment by tahpot** [comment]
Ok to merge these changes.

@ryank000 and @tahpot will review the multi sig documentation and then the three of us can jump on a call and walkthrough together.

**Review by tahpot — APPROVED** [review]

**Review by ITStar10 — COMMENTED** [review]
All working

**Pull request merged**
