### PR TITLE
Feature/106 create vda common

### LINKED ISSUE #106: [vda-common] Create vda-common
- All shared codes between contracts will moved to this contract
- Check and update package dependencies for all contracts

- Update `ChangeLog.md` files in all contracts
- Update `ReadMe.md` file for adding instructions.
- Check out dependencies and update `package.json` files.

### PR DESCRIPTION
**Pull request by ITStar10**
- Upgrade solidity versions to `0.8.18`
- Update hardhat configuration with the latest version
- Apply the same format to `ChangeLog.md` & `ReadMe.md`
- Created `VDA-Common` contract
- Upgrade versions of all contracts

### CODE REVIEW

**Comment by tahpot** [comment]
Thanks @ITStar10

That's a much more helpful description.

Please also tag the issue in the description for future as well (#106)

**Comment by tahpot** [comment]
Testing process:

- [x] Code review
- [x] Run all the unit tests

Release process:

- [ ] Publish `vda-common` and `vda-verification-base` to npm
- [ ] Update dependencies (stop using `yarn link`) to use new packages
- [ ] `yarn install` everything from scratch
- [ ] Build everything from scratch

**Review by tahpot — CHANGES_REQUESTED** [review]
Feedback:

- `DID-Linkage` tests fail with `Unable to force creation of storage context for this DID`
- `Verification-Base` produces a build warning `Function state mutability can be restricted to pure   --> contracts/TestContract.sol:107:5: function rawRecoverAddress ...`
- `VDA-SBT` build fails `Error HH404: File @verida/name-registry/contracts/EnumerableSet.sol, imported from contracts/SoulboundNFT.sol, not found.`

**Comment by ITStar10** [comment]
image

- VDA-DID-Linkge test works on my side.
The error is from the `client-ts` in the verida-js. Please try with another private key in the env file.
Compare the env file with the `.env.example`.

**Comment by tahpot** [comment]
Status update:

- [x] DID-Linkage tests fail with Unable to force creation of storage context for this DID
- [x] Verification-Base produces a build warning Function state mutability can be restricted to pure   --> contracts/TestContract.sol:107:5: function rawRecoverAddress ...
- [x] VDA-SBT build fails Error HH404: File @verida/name-registry/contracts/EnumerableSet.sol, imported from contracts/SoulboundNFT.sol, not found.

All good to merge.

**Review by tahpot — APPROVED** [review]

**Pull request merged**
